Repository Rebels-Y3S2/CSSE-BE, pull requests merged in 2022-11, with the labels that each got.

#28 Testscases/user
  services/__test__/testConfig.js
  services/__test__/user.service.test.js
  utils/constants/testConstants.js
Labels: Tests

#29 Fixed bug in userTests
  services/__test__/user.service.test.js
Labels: Tests, Bug fix

#31 Enhancement/template pattern
  index.js
  utils/InitializeBackend.js
  utils/constants/config.js
  utils/constants/loggerConstants.js
  utils/dbConnect.js
  utils/logger.js
Labels: enhancement
